# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_det <- function(matrix_list, celltypes_num, core_num = 1L) {
    .Call(`_scGeneNet_log_det`, matrix_list, celltypes_num, core_num)
}

log_det_block <- function(matrix_list, celltypes_num, p_GRN, core_num = 1L) {
    .Call(`_scGeneNet_log_det_block`, matrix_list, celltypes_num, p_GRN, core_num)
}

log_det_GRN <- function(matrix_list, celltypes_num, p_GRN, core_num = 1L) {
    .Call(`_scGeneNet_log_det_GRN`, matrix_list, celltypes_num, p_GRN, core_num)
}

ADMM1 <- function(Theta_mat_sparse, s_sq_mat_all, obs_mat, mu_vec_all, m_mat_start_all, S_depth, var_index_m, GRN_num, core_num = 1L, ADMM_maxiter = 50L, th = 1e-3, rho_input = 0.1, is_rho_input = TRUE, is_rho_constant_nonGRN = TRUE, is_update_nonGRNpart = TRUE) {
    .Call(`_scGeneNet_ADMM1`, Theta_mat_sparse, s_sq_mat_all, obs_mat, mu_vec_all, m_mat_start_all, S_depth, var_index_m, GRN_num, core_num, ADMM_maxiter, th, rho_input, is_rho_input, is_rho_constant_nonGRN, is_update_nonGRNpart)
}

Newtown <- function(diag_Theta_all, s_sq_mat_start_all, m_mat_all, S_depth_use, var_index_s, p_GRN, core_num = 1L, newtown_maxiter = 50L, th = 1e-3, low_bound = 1e-8, is_update_nonGRNpart = TRUE) {
    .Call(`_scGeneNet_Newtown`, diag_Theta_all, s_sq_mat_start_all, m_mat_all, S_depth_use, var_index_s, p_GRN, core_num, newtown_maxiter, th, low_bound, is_update_nonGRNpart)
}

Theta_fun <- function(U_mat, Theta_mat_list, m_mat_list, s_sq_mat_list, p_GRN, lambda_use, zero_GRN, stop_threshold, var_index_Theta, penalize_diagonal = FALSE, zero_GRN_use = FALSE, core_num = 1L) {
    .Call(`_scGeneNet_Theta_fun`, U_mat, Theta_mat_list, m_mat_list, s_sq_mat_list, p_GRN, lambda_use, zero_GRN, stop_threshold, var_index_Theta, penalize_diagonal, zero_GRN_use, core_num)
}

scGeneNet_optim <- function(celltypes_label_input, U_mat_input, mu_mat_input, m_mat_list_input, s_sq_mat_list_input, pi_vec_input, obs_mat_input, S_depth_input, gene_GRN_index_use_input, Theta_mat_list_input, zero_GRN_input, if_zero, log_det_vec_input, lambda_use, penalize_diagonal, maxit_nonGRN, MS_update_threshold, maxit, minit, ELBO_threshold, verbose, ADMM_max_step, ADMM_threshold, Newton_max_step, Newton_threshold, Theta_threshold, core_num, U_fix) {
    .Call(`_scGeneNet_scGeneNet_optim`, celltypes_label_input, U_mat_input, mu_mat_input, m_mat_list_input, s_sq_mat_list_input, pi_vec_input, obs_mat_input, S_depth_input, gene_GRN_index_use_input, Theta_mat_list_input, zero_GRN_input, if_zero, log_det_vec_input, lambda_use, penalize_diagonal, maxit_nonGRN, MS_update_threshold, maxit, minit, ELBO_threshold, verbose, ADMM_max_step, ADMM_threshold, Newton_max_step, Newton_threshold, Theta_threshold, core_num, U_fix)
}

